### ISSUE TITLE
Don't duplicate resource feedback in feedback loop

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#181]
- [x] If a user has already provided feedback on a resource, that resource will not appear in their feedback loop

**Comment by samhstn** [comment]
I'm not sure if I understand this issue, or if it has already been resolved.

On the current [live site](http://www.londonminds.co.uk/), I click on two resources and reach the feedback loop state for them.

![screen shot 2017-08-29 at 13 24 13](https://user-images.githubusercontent.com/15983736/29820751-6bad5bd0-8cbd-11e7-96f4-fe50e1dcf276.png)

I fill in my feedback for the first one and submit it.

![screen shot 2017-08-29 at 13 25 24](https://user-images.githubusercontent.com/15983736/29820788-88a5a5c6-8cbd-11e7-8fae-792c17fc59d6.png)

From now on I won't have that resource in my feedback loop.

![screen shot 2017-08-29 at 13 25 54](https://user-images.githubusercontent.com/15983736/29820807-9a5a4646-8cbd-11e7-8db1-84fc9d9922f1.png)

This happens weather the feedback was submitted in the feedback loop block or inside the resource block.

It seems that this fulfils what this issue is requesting. @ellemindwave could you elaborate on this issue

**Comment by samhstn** [comment]
@Danwhy has clarified that if a user has clicked on a resource and left feedback, then we never want to include that resource in the feedback loop. @ellemindwave is this correct? Do we also want to ask users again if they have clicked the cross as they do to not want to leave feedback?

**Comment by ellemindwave** [comment]
@shouston3 Yes that's correct.

If they have previously left feedback on a resource then they don't need to be asked again, as well as if they have previously clicked the 'x' sign.
