### ISSUE TITLE
Creation of project partners box

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#193]
![image](https://user-images.githubusercontent.com/16775804/29913348-d3d5391a-8e2c-11e7-8bca-6fdbb6f264b1.png)

- [x] box to sit underneath the hero block
- [x] content in box to be pulled through from the pages themselves / content is unique to the box?
- [x] box is able to be moved to sit elsewhere on page

@Cleop @reddog @sarahwelton the final decision on this one has escaped me... 

Did we decide that the content in these boxes would be pulled through from the pages themselves? or that the boxes would have unique content in them to introduce the page..?

**Comment by reddog** [comment]
@ellemindwave I think we didn't make a final decision because we weren't sure:

1.  which is the best (technical) solution
2.  which is the best (quickest to implement) solution
3.  which is the best (extendable for future design/functionality) solution.

I think that @Danwhy & @shouston3 were going to spend a short while (how long?) looking in to these points and then we'd be able to make an informed decision on what was best for the project.  Does that sound about right?

**Comment by Cleop** [comment]
I thought that from an admin perspective that someone (@sarahwelton?) thought it would be easiest if these boxes were added to from the homepage (rather than the project partners page). 

Given the progress @shouston3 and @Danwhy are making so far through this sprint I think we have time for either implementation so it's more a question of what makes most sense/use for the MV team.

But I'm open to direction because my memory isn't crystal clear either...

**Comment by reddog** [comment]
@cleop Great to hear progress is good this sprint!

It would probably still be useful for @Danwhy & @shouston3 to spend a little time giving a response to https://github.com/LDMW/cms/issues/193#issuecomment-325942686  That would help ensure we're going down the right route for the project as a whole.  Is that something that could be given a relatively small amount of time to?

**Comment by Danwhy** [comment]
As we already have the functionality to create static pages, all we really have to do to make these boxes as flexible as they need to be is to add a description box on the static pages admin side which can be pulled through, and a checkbox to make them display in a certain place (in this case project-menu or something similar, but we would also have a footer checkbox for static pages in the footer etc.).

This would allow for the most flexibility, as it means boxes can be added/removed from the homepage as necessary. I don't think it would take much more time than just hardcoding a certain number of boxes on the homepage admin, maybe another two hours, so would probably be the most beneficial way to implement it.

**Comment by reddog** [comment]
@Danwhy Thanks for the feedback.

I can see what you mean regarding adding the following to the admin page for "static" pages:

1.  description box
2.  checkbox(es) to display in certain homepage sections

Whatever options you make on the "static" page settings, these would be set for that static page, ie it wouldn't be possible to use a different description if the static page were linked to from multiple sections.

Also thinking further ahead, if a static page were linked to from multiple pages (ie other than just the homepage - this isn't something that's been scoped out at all yet, just a future-gazing guestimate), then having the description box on the home page admin screen would allow for greater flexibility.

The home page settings should then contain:

1.  "static" pages to be linked to, and their display order
2.  for each "static" page, a description box (moved from the static page settings)

If you wanted to take it one stage further, you could have both the description box on the static page and on the home page.  If the description is filled in for that static page in the home page settings then use that text, otherwise use the description from the static page.  That would reduce re-keying where a single description should be used in multiple places, whilst giving the flexibility to override it on a case by case basis.

I don't know how long these would take to implement.  Time to implement may help decide if they're overkill (at this stage at least).

Certainly, having a description box on the static page itself (and pulling through to display on the user viewable home page) is at least a version 1 of this requirement.

**Comment by Danwhy** [comment]
Having the pages and description boxes on the home page makes sense, and I don't think it would actually take any longer to do it that way. @shouston has just done some work on adding multiple fields to wagtail for the footer images, so we could implement this in the same way.

**Comment by reddog** [comment]
@Danwhy Thanks for that.  Since you already have a similar example with @shouston3's work, as you say, that should help development on this piece.

To confirm, will you be hard-coding the number of partner boxes?  How would the display look if there were only one (if that is an option)?  Will it be possible to add an arbitrary number of such boxes?

**Comment by Danwhy** [comment]
@reddog Yeah, adding an arbitrary number is what @shouston3 implemented for the footer so we can do that. We'll evenly space them based on how many have been added.

**Comment by reddog** [comment]
@Danwhy Thanks for that.

Would it be more in tune with the given the design to wrap on a two per line basis, horizontally centering if there is only one box on a line?

**Comment by Danwhy** [comment]
Live on http://ldmw-staging.herokuapp.com/
