### ISSUE TITLE
Cookie banner

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#203]
- [x] to appear underneath the Beta banner
- [x] @indiamindwave24 agreed happy for the standard GDS approved cookie banner to be used (in terms of styling )

**Comment by samhstn** [comment]
@ellemindwave The cookie banner I previously implemented was at the bottom your screen. It turns out that the banner being in this position is quite a lot easier to implement. Would you be ok with it being added here instead? Perhaps we can test it out at the bottom and see if we would like it moved

**Comment by ellemindwave** [comment]
@shouston3 Yes that's fine, let's try it how you implemented it before, and if it turns out in testing that there are any major issues with it then we can reassess 👍

**Comment by samhstn** [comment]
This is now up on the [staging site](https://ldmw-staging.herokuapp.com/)
