### ISSUE TITLE
Styling and implementation of Self-assessment when it appears in listings

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#277]
- Different styling for Self-Assessment when it appears as a resource

- In Wagtail, ability to categorise a resource as a 'resource' 'tip' or 'assessment' (potentially more options in future)

- Take sleep/anxiety/depression/stress assessment box to appear in filtered searches as a module - boxes will require : title, text field, url, tag field. 

This will have new styling

**Comment by Danwhy** [comment]
Just awaiting styling for this now

**Comment by sarahwelton** [comment]
<img width="1027" alt="screen shot 2017-09-14 at 15 38 36" src="https://user-images.githubusercontent.com/26305143/30435908-d3985612-9962-11e7-8bd7-7d7d99b3ad52.png">

Have kept styling simple so that it should be fairly simple to implement if @indiamindwave24 would like to adjust colours - but go with this for now @Danwhy
