### ISSUE TITLE
Beta strip has disappeared on homepage 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#314]
Noticed this when looking for link to self assessment, beta banner is gone on homepage:

![screen shot 2017-09-08 at 10 12 12](https://user-images.githubusercontent.com/26304634/30204681-354f2c12-947e-11e7-90d4-56ffb49bbd65.png)

**Comment by samhstn** [comment]
@ellemindwave That's because it has been removed in the admin view:

![screen shot 2017-09-08 at 13 50 16](https://user-images.githubusercontent.com/15983736/30212412-b96d0d2a-949c-11e7-9750-ac494dcb85eb.png)

https://www.londonminds.co.uk/admin/pages/153/edit/

Clicking `revisions` on the bottom right corner shows that @sarahwelton removed the banner yesterday evening

![screen shot 2017-09-08 at 13 51 58](https://user-images.githubusercontent.com/15983736/30212447-f1dd148e-949c-11e7-8206-0457859f7853.png)

If you would like to add it back in, just revert the homepage back to the previous state before Sarah's removal
