### ISSUE TITLE
'Back to results' button on individual resources pages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#467]
When clicking through to an individual resource page, it would be good if there could be a 'back to results' button

**Comment by sarahwelton** [comment]
However - not if we link directly to the page as this wouldn't make sense.

We can't have back to topic either as a resource can sit in multiple topics. 

Can a "back button" appear **only** if they have clicked from a listing page?

**Comment by iteles** [comment]
Changing the estimate here as with @sarahwelton's requirement (which we'll need to clarify a little further), this needs to be done with session storage and Javascript.

**Comment by reddog** [comment]
@iteles You mentioned that you need further clarification on this - can you please let us know what's required from your side?

Why is implementation with session storage and JavaScript?  Am I right in thinking that the site has been (at least part) designed to work with JavaScript turned off?

This could be done server-side.

## Current

1.  on results page, a series of resources are displayed.  Each resource has a link to its own page.

2.  clicking on a resource link opens the page for that resource

## Proposed

1.  on results page, a series of resources are displayed.  Each resource has a link to its own page.  Included in this link is a `go back` parameter which is a link to the currently viewed results page

2.  clicking on a resource link opens the page for that resource.  If there is a request parameter value for `go back` then that link is used as the destination for the `back` button.

## Issues

1.  it would be possible to *hijack* the `go back` link by creating a URL like this: www.good-thinking.uk/resource?go_back=http://www.somewhereelse.com/other-page (with appropriate URL encoding).  This could be fixed by only permitting the `other-page` etc. part in the `go back` parameter.

2.  using a `go back` parameter *could* potentially *give away* information to other people, ie the user could share a link to a resource with others and the back button would then *give away* what options they selected on the results page.

## New Proposal

1.  on results page, a series of resources are displayed.  Each resource has a link to its own page.  A server-side session cookie is set for the `go back` page being the URL of the results page.

2.  clicking on a resource link opens the page for that resource.  The server-side session cookie is queried
to get the link for the `go back` button.

This *new proposal* keeps all processing server-side, removes reliance on JavaScript and *gives away* no information if a link for a given resource is forwarded on.

**Comment by Danwhy** [comment]
https://ldmw-staging.herokuapp.com/trouble-sleeping/ 
When you go to a resource page from a topic page, there will be a link back to that particular page. The link will not appear if you come into the resource directly via the url.
