### ISSUE TITLE
Self Assessment - has age limit page barrier

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#468]
Very odd... went to self-assessment from footer block, and clicked 'next' on first explanatory question, and then met with this screen (have not put age in yet)

![screen shot 2017-09-21 at 16 14 07](https://user-images.githubusercontent.com/26304634/30703601-16575004-9ee8-11e7-8104-9229be9820b9.png)

If you select 'Hard stop' it takes you through to the assessment anyway....

**Comment by Danwhy** [comment]
@ellemindwave This seems to be a problem on Expert 24's end. I've figured out that the issue is the `@usertype=300` part of the url that was asked for in https://github.com/LDMW/cms/issues/331, as when I remove this from the url, the assessment works fine again.
I think this is quite a recent problem, as the assessment was working fine with this parameter until Wednesday.

**Comment by ellemindwave** [comment]
Thanks @Danwhy - are we able to remove this bit of the URL so that assessment works fine again as an interim fix?

**Comment by Danwhy** [comment]
Yes, I'll do that
