### ISSUE TITLE
"Selected" state on tags to show once clicked

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#494]
At the moment, when you click on a tag, it remains in "hover" state - presumably because the user is still "hovering" over the button. Could we do something to make it appear in it's "selected" state once clicked?

**Comment by iteles** [comment]
This is typical browser behaviour, as you say @sarahwelton it's because the mouse is still on the tag, as soon as you move it, the selected state appears.

We can look to make this happen with Javascript (removing the hover state on click) and would have to watch out to ensure that the hover state is restored if somehow the tag is unselected, though this would only work with Javascript turned on.

@sarahwelton Can you confirm that we want to counter the typical browser behaviour?

**Comment by reddog** [comment]
@iteles Could this

> typical browser behviour

be because we're effectively mis-using `buttons`?  We're using a regular button to represent an on/off state.

If a CSS class is added/removed on button click with JS then that should largely handle it.

You are right that

> this would only work with Javascript turned on

Does this mean that maybe the implementation isn't correct?  Maybe these buttons are acting as `checkboxes`?  Maybe a separate issue could be opened to replace these buttons with appropriately styled checkboxes which would work with JavaScript on or off?
