### ISSUE TITLE
Need to amend the "page titles" to show "resource  |  service name"

### ISSUE THREAD

**Issue by sarahwelton** [LDMW/cms#506]
Page title should be this:

<img width="1143" alt="screen shot 2017-09-26 at 12 26 47" src="https://user-images.githubusercontent.com/26305143/30858563-1e6611d0-a2b8-11e7-82be-a967f7a3e8e8.png">

But looks like CMS is overriding so it is appearing as this: 

<img width="641" alt="screen shot 2017-09-26 at 12 27 12" src="https://user-images.githubusercontent.com/26305143/30858572-28848890-a2b8-11e7-9b9e-4fc058b10a15.png">

We need it to **not** show "Good Thinking" first

**Comment by reddog** [comment]
@Danwhy Out of interest, is the site name `Good Thinking` in this example, being pulled for a single setting within the CMS, or would it have to be changed on each page?

Having it on one setting will ensure consistency and correct spelling and minimise work when creating/editing pages or if changing name in the future.

@sarahwelton Is your pattern of `resource name | site title` the same for **all** pages on the website?  Or does there need to be some flexibility to not display the `| site title` part on some pages?

If it's the latter then probably the fix is just to use whatever is entered in the `page title` on the settings for that page, and to never append the site title (which does make more manual maintenance work - maintaining consistency).

**Comment by Danwhy** [comment]
Based on what was asked for on https://github.com/mindwaveventures/cms/issues/357#issuecomment-330149744, the title was hardcoded to be `Good Thinking | {seo title of the page}`.
It would be quite simple to have the title of the home page in place of the Good Thinking part, meaning it's easy to change, then the seo title to only show if defined.

**Comment by Cleop** [comment]
Conclusion: swap the current order so that it is {title} | Good Thinking throughout the entire site.

**Comment by Danwhy** [comment]
This is now live on staging for testing.
The page title is now {title of page} | {site title} when a page has an seo title, or just {site title} when it doesn't.
Site title is defined in Wagtail in Settings -> Sites.
