### ISSUE TITLE
Test compatibility on IE

### ISSUE THREAD

**Issue by Cleop** [LDMW/cms#518]
Test the site on IE8-10 to follow GDS guidelines for functionality. Testing on IE11 for being 'compliant'.

**Comment by katbow** [comment]
**IE8-10**
* [x] Buttons on home page aren't working - does nothing when clicked on. I think it's because they are relative links but missing the slash 
![image](https://user-images.githubusercontent.com/1287388/31232885-03ebea28-a9e3-11e7-8b85-13a3bf639472.png).
* view pros and cons button does not work on resources so the pros and cons are not showing anywhere. - moved to  #545

**IE11**
* [x] The "Get more info and read comments" button has the link/button in the wrong order which makes it difficult to click. The link is over the text, but should be around the whole button (this goes for chrome too, but it is particularly difficult on IE.) Reverse `<a>` and `<button>` tags in the code below.

```
<button class="f6 link dib ph3 pv2 br1 pointer nunito tracked inner-shadow-active lm-white lm-bg-dark-turquoise lm-bg-white-hover lm-dark-turquoise-hover ba b--lm-dark-turquoise">
  <a href="/{{page.parent}}/{{page.slug}}/">Get more info and read comments</a>
</button>
```

**Comment by katbow** [comment]
I'm going to implement the fixes for this now - finished reviewing all of it.

**Comment by katbow** [comment]
The pros and cons bug was split into it's own issue #545 as it will take longer to implement than the T2h overall time limit for this issue.

**Comment by katbow** [comment]
@Cleop for closing this one off, who will be responsible for doing that? I am not sure if the mindwave have access down to IE8 to check it themselves.

**Comment by Cleop** [comment]
@ellemindwave - do you have a way of checking IE and different versions to test this issue? Alternatively we can close this if we've tested it at our end and label it a technical issue.

**Comment by ellemindwave** [comment]
I don't have a way of testing this right now, no. 
If you have tested it on IE 8 lowest and it works then happy for you to close at your end
