### ISSUE TITLE
All badges to be same shape as the local badge

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#553]
-  [x] Badge shape should be same as local badge

- [ ] Badges shouldn't be on same line as tags, should be in the very right hand top corner and not cause tags to go onto next line

<img width="662" alt="screen shot 2017-10-06 at 2 50 19 pm" src="https://user-images.githubusercontent.com/26304634/31281147-8a5bd546-aaa6-11e7-9a9d-ed41fd8b074f.png">

**Comment by katbow** [comment]
@ellemindwave Should only the light turquoise badges be rounded corners, or should orange tags also be rounded? Also, do these badges only appear on resources, or are they anywhere else I should be aware of?

**Comment by ellemindwave** [comment]
@katbow all badges should have rounded corners please. 
These badges only appear on resources on the listing pages and on the individual resources page

**Comment by katbow** [comment]
@ellemindwave great, thanks! I do have another question regarding the second point.

> Badges shouldn't be on same line as tags, should be in the very right hand top corner and not cause tags to go onto next line

I have moved the badges to the top right hand corner, however it can still 'push down' the tags when there are multiple badges. Don't mind the colour of the first badge in the image below, I just picked a random colour for testing it out.

![image](https://user-images.githubusercontent.com/1287388/31347275-c244903c-ad13-11e7-9245-2fc157684766.png)

It could be moved down into a separate div so the tags always appear below whatever level the badges go down to. I'm not sure this is desirable, however, since it could mean a large white space if there are a lot of badges. 

What are your thoughts on this?

**Comment by ellemindwave** [comment]
Hi @katbow - just chatted about this and it seems that initially anyway, there won't be many resources that have 2 badges. 
So what you have suggested is fine (in terms of it sitting on same line). 

 - - - It could be moved down into a separate div so the tags always appear below whatever level the badges go down to. I'm not sure this is desirable, however, since it could mean a large white space if there are a lot of badges. - - - 


Correct - big white space wouldn't be desirable 👍

**Comment by katbow** [comment]
@ellemindwave I added some badges to the top resource [here](https://ldmw-staging.herokuapp.com/trouble-sleeping/)
