### ISSUE TITLE
On mobile devices the 'AWMS?' box has a drop shadow

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#573]
- [ ] this happens on iPhone 6, chrome
- [ ] also occurs on Mozilla Firefox

![image uploaded from ios 1](https://user-images.githubusercontent.com/26304634/31343195-cf96b470-ad06-11e7-99b9-e6af3a780d96.png)

**Comment by katbow** [comment]
@ellemindwave should this just be flat then? are there any borders?

**Comment by ellemindwave** [comment]
Yes please - just flat as it appears on the desktop version of the site
![screen shot 2017-10-10 at 12 37 33](https://user-images.githubusercontent.com/26304634/31384671-d2af8f5e-adb7-11e7-86be-8ac0a2f8fd30.png)

**Comment by katbow** [comment]
@ellemindwave on the desktop version there is a shadow (which is the same shadow styling as the one that's applied on mobile).
![image](https://user-images.githubusercontent.com/1287388/31384792-73b1d0c4-adb8-11e7-9dd4-4a2fc434a47b.png)

If I turn the shadow off on desktop, it ends up looking like this:
![image](https://user-images.githubusercontent.com/1287388/31384818-8cfa83dc-adb8-11e7-9916-dc7e33d50cab.png)

And if I turn this off on mobile it looks like this:
![image](https://user-images.githubusercontent.com/1287388/31384921-010d62f8-adb9-11e7-878a-88b7f01366ab.png)

**Comment by ellemindwave** [comment]
@katbow yes please, turn off the drop shadow so that it looks how it does in your example, above.

**Comment by ellemindwave** [comment]
@katbow on mobile this still looks the same to me, with the drop shadow still there:

(iPhone 6, chrome)

![image uploaded from ios 6](https://user-images.githubusercontent.com/26304634/31437908-e68fe8da-ae7e-11e7-97ea-cb8fdbbe680c.png)

**Comment by katbow** [comment]
Sorry @ellemindwave, this was due to a misunderstanding of which shadow was being referred to. 
In [this comment](https://github.com/mindwaveventures/cms/issues/573#issuecomment-335446916) I had removed the shadow from around the entire section. 

I'll look into what's causing the shadow on the text box!

**Comment by katbow** [comment]
@ellemindwave I can't seem to get this to show up in the browser. It looks like this for me:

![image](https://user-images.githubusercontent.com/1287388/31447898-02028e12-ae9b-11e7-8950-e5339b1175d2.png)

Do you only see this if you are using the actual device (iPhone6) and browsing on chrome?
Is this the same for mozilla?

**Comment by katbow** [comment]
Ahh I think I see what the issue is here @ellemindwave. This is default styling on IOS. 

The default styling can be removed with 
```
.no-ios-defaults {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```

However this can cause other desirable styling to be removed, which results in this across all devices.
![image](https://user-images.githubusercontent.com/1287388/31449227-43052958-ae9e-11e7-9b7a-1d4818ee831a.png)

Instead I used `background-clip: padding-box;`, which ["extends the background to the outside edge of the padding. No background is drawn beneath the border."](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip). I checked on an actual iPhone and this removed the input shadow without any other wonky effects.
