### ISSUE TITLE
Implement new Good Thinking logo and button colour change

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#622]
Awaiting mock-ups and assets from @sarahwelton later today

**Comment by sarahwelton** [comment]
New logo to replace "home" button (after all that work!!) Thanks guys. 

**PNG, EPS and SVG attached** 
[Good_Thinking_logos.zip](https://github.com/mindwaveventures/cms/files/1379904/Good_Thinking_logos.zip)

**Mockups here**

![homepage](https://user-images.githubusercontent.com/26305143/31506007-26f9aac4-af6e-11e7-89a1-7d2190cc75ca.png)
![listings page](https://user-images.githubusercontent.com/26305143/31506008-271134b4-af6e-11e7-8a2a-fe3b114bf8a1.png)
![mobile home](https://user-images.githubusercontent.com/26305143/31506009-276a45c2-af6e-11e7-9dca-2e7867448aee.png)

**Comment by katbow** [comment]
On mobile, I see that the logo is now part of the beta banner. Does this mean that the "Home" text is now removed from the open burger menu?

**Comment by ellemindwave** [comment]
Self-Assessment button to be different colour - see beta banner

<img width="1087" alt="screen shot 2017-10-12 at 17 10 05" src="https://user-images.githubusercontent.com/26304634/31536148-84cbfea4-aff5-11e7-93c6-08db9a3c0c7f.png">

**Comment by ellemindwave** [comment]
@sarahwelton says: 

I'd keep it in there
Save time and no harm having both

**Comment by katbow** [comment]
There's a couple of things on here that I want to verify if they are actual style changes or not
* Burger menu background is transparent and icon is white (instead of white background and black icon)
* The following section with the orange background
![image](https://user-images.githubusercontent.com/1287388/31540971-0d46d1b4-b005-11e7-83c2-4cd3dee480a4.png)
Which is currently
![image](https://user-images.githubusercontent.com/1287388/31540992-1aca7ebc-b005-11e7-8429-7186c26623d5.png)

* There are some background colours/image here, and the "Are we missing something?" box is wider than the topic cards above.
![image](https://user-images.githubusercontent.com/1287388/31541037-4faa9374-b005-11e7-8235-e4f67b4267e4.png)

Please let me know if these are changes that need to be made or not.

**Comment by katbow** [comment]
Verified with @ellemindwave that the [last point here](https://github.com/mindwaveventures/cms/issues/622#issuecomment-336407998) can be ignored.

Double checking on the other points!

**Comment by ellemindwave** [comment]
@katbow burger menu should sit on transparent background and be white please

**Comment by ellemindwave** [comment]
@katbow just checking that you saw the last screenshot that I uploaded, that showed the self-assessment button being a different colour to the others? it's not showing up for me

**Comment by katbow** [comment]
@ellemindwave Oh I thought that was referring to the colour when active/inactive. I'm not sure what you mean. Do you mean it need to turquoise borders/text all the time and the urgent help button is grey all the time?

**Comment by ellemindwave** [comment]
@katbow found out the cause of the misunderstanding - I thought the SA button was to be different, but no..

Urgent support button should be navy blue, and when selected by grey as it currently is when selected 👍 

Apologies for confusion

**Comment by katbow** [comment]
spoke with @ellemindwave to confirm: The Self assignment button will still exactly as is, however the get support button will have #242E50 as the border colour/text colour. On hover, this will change to #242E50 as the background & white text.

**Comment by katbow** [comment]
@ellemindwave I just noticed a potential problem with having the burger menu icon white. There are some pages which do not have a hero image so the icon would not be visible here, such as on individual resources like below.

![image](https://user-images.githubusercontent.com/1287388/31550103-1e67dcb8-b028-11e7-9c6b-060d1134c6b3.png)
