### ISSUE TITLE
Option to left align text on static pages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#657]
We need the option to have the text aligned to the left of the page (in line with the left hand side of the blocks below it) on static pages.
Looks a bit odd stuck in the middle now that the character limit is 80 per line

![screen shot 2017-10-16 at 10 15 09](https://user-images.githubusercontent.com/26304634/31604417-1f57bd70-b25b-11e7-8aad-d397833a2a54.png)

**Comment by reddog** [comment]
@ellemindwave Should this be a per-page option within the admin menu?  Something like `body alignment` (as distinct from `text alignment`, which would be the alignment within the block)?

![image](https://user-images.githubusercontent.com/151362/31725984-98e3cad0-b41d-11e7-8861-879309b5139b.png)

**Comment by Cleop** [comment]
@ellemindwave - do we need the ability to have both left and centre aligned text or from what you're saying now about the 80 char limit, would you always prefer this text to be left aligned?

**Comment by reddog** [comment]
@Cleop There is already a `text alignment` option.  Would you propose removing that?  If it were kept in would that retain a certain level of flexibility?

**Comment by Cleop** [comment]
Following our chat this morning. @ellemindwave clarified that this issue may be solved by #663 once the details for #663 have been determined. 

Apologies @reddog for my use of the term 'text alignment', I meant to refer to the alignment of the div on the page as opposed to the alignment of the text within a <p> if that makes sense? In summary, I think that this issue is a specific use case of #663 not to do with text alignment.

**Comment by ellemindwave** [comment]
Will be solved by issue #663
