### ISSUE TITLE
Ability to have columns on static pages

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#663]
Not just one column that sits in the middle of the page

**Comment by sarahwelton** [comment]
If less copy, content column should be aligned to the left hand side of the screen. In line with the left hand footer blocks.

**Comment by reddog** [comment]
@sarahwelton Is your comment the same as #657 or something different?

@ellemindwave Is this issue explicit enough?  How many columns?  Fixed number of columns or variable?  What gap between them?  How would new columns be added within the CMS?  Or would columns be automatically displayed in a wide-screen responsive way?

**Comment by ellemindwave** [comment]
How many columns? depends on screen size. Small screens 1, laptops & standard desktops 2, iMacs and other very large screens 3

Would be good to discuss with @katbow and @Danwhy at what point they think it would make sense for the text to start a new column. At a certain number of lines? paragraphs? what would be easiest?
There would need to be some rules to avoid a lonely paragraph sitting on its own. 

The gap between would just be the normal padding distance as the rest of the site, as seen below. The distance of the 'about' in the left hand paragraph and the 'support' in the right hand one. 

![screen shot 2017-10-20 at 14 46 16](https://user-images.githubusercontent.com/26304634/31823907-86594e56-b5a5-11e7-91e4-4f22daecedc9.png)

**Comment by katbow** [comment]
> at what point they think it would make sense for the text to start a new column. At a certain number of lines? paragraphs?

It depends if it's alright having a paragraph split across columns. If you don't want that, then it's probably best to split it based on paragraphs rather than lines. 

Would this apply to every page and have it always split across 2+ columns on desktop?

> If less copy, content column should be aligned to the left hand side of the screen. In line with the left hand footer blocks.

This comment makes it seem like it won't *always* split on every page. What is the cut off point where it no longer splits? 

If text is both left aligned & keeps in mind #641, then we would be looking at something like this:

![image](https://user-images.githubusercontent.com/1287388/31886711-6475d94a-b7ed-11e7-9c23-192ed1d826af.png)

**Comment by sarahwelton** [comment]
I think that above example is great.  So perhaps any more than 4 paragraphs = additional columns. 

I doubt we can avoid the issue of having a lonely paragraph though, can we?

**Comment by katbow** [comment]
We'll need to wait to work on this as we had a quick chat and still had some questions which might be best to have a discussion about. If you are free later this afternoon @sarahwelton feel free to grab one of us so we can clear up the requirements from a user and technical perspective.

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/31954822-7bc71f0e-b8de-11e7-9ede-3aad60cc7fdc.png)
Screenshot from @sarahwelton of XL screen like iMac

Still to come from @sarahwelton the px at which 1 column should turn to 2 and 2 columns turns to white padding and larger fonts.

@Cleop jumping on your comment here and adding in that the H3s (titles for the footer blocks) are 28px (from Sarah!)

**Comment by sarahwelton** [comment]
I could do with some advice here I think...! 

My guess is that a normal ipad in portrait should be one column - but ipad pro should use the larger fonts shown in the screenshot above - still with one column.  

Once ipad (normal or pro) turns landscape then it should become two columns. ipad mini would still be one column at landscape size.. 

Large desktops (1680+?) should use the larger fonts. 

Can you guys all chip in and let me know what you think before we go ahead? 

@ellemindwave @indiamindwave24 @Cleop @Danwhy @katbow

**Comment by Danwhy** [comment]
@sarahwelton I think the larger font size will look a little too large on the ipad pro, and I also think it will be a bit weird to have the font size get bigger for ipad pro, then smaller again on a normal desktop. 

Is the large font size going to be site-wide on the large desktops? I'm assuming it is since the 80 character limit is going to be applied site-wide now

**Comment by sarahwelton** [comment]
Okay thanks Dan - Leave it as one column at normal size on ipad pro then. 

@indiamindwave24 - I've done a mock up for the static pages for large desktops (eg your giant imac!) where I have increased the font sizes (see above). 

Could you advise on whether you think these font sizes should be implemented across the site? It sounds like it makes sense but I'm nervous of saying yes when I can't envisage what it looks like! (I am also aware you aren't working on your iMac today so this could be a tricky one to answer!)

**Comment by indiamindwave24** [comment]
I would be happier if the larger font size was just for static pages. 

Concerned that enlarging the text site-wide could potentially have a knock on effect for tags and overlapping items etc and we don't have any time to fix these! 

So just larger text on static pages (on larger screens), please 😄  Thanks @Danwhy 👍

**Comment by sarahwelton** [comment]
![imac_v2](https://user-images.githubusercontent.com/26305143/32008484-378e106a-b9a4-11e7-81e2-fe9993cd7338.png)

As discussed - amended font sizes:

H1 - 45px
H2 - 30px 
H3 - 26px 
Body copy - 18px / line height 28px 

This does mean that the columns will need to be slightly smaller due to the line width - and this will need to be reflected in the footer blocks as well. So additional white space on each side of the browser, pushing the main content further into the page. (Also applies to header / navigation and footer). Space between columns can also be slightly increased if this is helpful to dev. 

@Danwhy hope this makes sense?

**Comment by ellemindwave** [comment]
@Danwhy the font size on larger screens seem to have increased on pages apart from static pages. 
and something odd is going on on large screens: 

Above @indiamindwave24 stated that the font size should only be increased on static pages, nowhere else.

I believe @indiamindwave24 has spoken with @Cleop about this to get it fixed

<img width="2064" alt="screen shot 2017-10-26 at 10 25 23 am" src="https://user-images.githubusercontent.com/26304634/32047118-e89356d4-ba3c-11e7-9e8c-e1d52974296b.png">
<img width="2027" alt="screen shot 2017-10-26 at 10 33 24 am" src="https://user-images.githubusercontent.com/26304634/32047143-f8b57fce-ba3c-11e7-99b0-9d9956a37aa6.png">
<img width="2560" alt="screen shot 2017-10-26 at 11 01 54 am" src="https://user-images.githubusercontent.com/26304634/32047473-ea55841e-ba3d-11e7-8ecf-04cd1bf60519.png">

**Comment by Danwhy** [comment]
@ellemindwave Sorry about that, this happened because I deployed everything this morning except the changes for the columns. I didn't realise I'd accidentally included the code to increase the font sizes, which I had later modified to only affect the static pages. This should all be fixed with the deploy of the static page/column code.

**Comment by ellemindwave** [comment]
Ah I see - good to know! Thanks @Danwhy

**Comment by Danwhy** [comment]
Columns can be added in wagtail to static pages by adding the text to a column-left block and a column-right block: see https://ldmw-staging.herokuapp.com/admin/pages/131/edit/ and https://ldmw-staging.herokuapp.com/admin/pages/131/edit/ for an example
