### ISSUE TITLE
Resource titles error on listing page (large screen)

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#682]
iMac 27inch 4k 

<img width="1572" alt="screen shot 2017-10-17 at 3 06 44 pm" src="https://user-images.githubusercontent.com/26304634/31673274-c1e4fb7e-b356-11e7-8dc7-9583028d31ba.png">

**Comment by katbow** [comment]
This is one that will need to wait until I have a larger screen to test on. Can check it out tomorrow!

**Comment by katbow** [comment]
I think this is happening when there are no badges on a resource. The h2 tag for the resource titles is `display: inline` so that the badges can float in the top right corner beside them (instead of being pushed underneath).

I changed the continue reading paragraph below this (the one that is pushing to the right of the title on large screens) to `display: block` so that no elements can go next to it on either side. We will need to check it out, but this should fix the problem 👍 .

**Comment by katbow** [comment]
@ellemindwave or @indiamindwave24 can this be checked on the large screen to see if my reasoning worked as expected? If not I'll also work from the large screen at some point to check it out. Thanks!

**Comment by indiamindwave24** [comment]
Apologies @katbow -- did not see this yesterday. You are free to use my computer in the office whenever you want :)
