### ISSUE TITLE
Add jQuery

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#684]
Add jQuery to the site

**Comment by reddog** [comment]
Can we use a CDN such as https://developers.google.com/speed/libraries/#jquery

**Comment by iteles** [comment]
@ellemindwave @reddog Could you please clarify the user story for adding jQuery to the site?
We would need more information in order to understand the requirement and the expected benefits to the users.

**Comment by reddog** [comment]
@iteles Of course.  It would be useful from our perspective to know what different implementations are possible depending on what the user story would be.

I believe that the benefit is that jQuery's selectors could be used to identify DOM elements via Google Tag Manager.

It would be useful if you foresee any negatives of having jQuery included.

**Comment by ellemindwave** [comment]
From FE - Setting up tags in GTM is easier if jQuery is available so we can identify specific elements in the DOM. From there we can create rules and use additional bits of dynamic information to add to the tags. In this case we’ve only had to do one workaround which works fine.

**Comment by ellemindwave** [comment]
@Danwhy @Cleop Please can we add JQuery to the site.

If there are necessary performance changes needed afterwards, then that may be the case, but we would like to have it added in and then we can test if it has affect performance or not. 
Thanks

**Comment by reddog** [comment]
@ellemindwave Are drops in performance expected?  I responded to @iteles comment above but have not heard back on any potential negatives.  See https://github.com/mindwaveventures/cms/issues/684#issuecomment-337653262

**Comment by iteles** [comment]
@reddog Cleo spoke to @ellemindwave on this yesterday morning. 

Drops in performance are par for the course with jquery if nothing is done to mitigate this as it's hefty. My understanding from your comment was that this could be done relatively effortlessly with JavaScript (everything in jquery can of course) which would certainly be preferable to mixing JavaScript and jquery but we don't have details around this. 

I wonder whether it would be useful for @cleop and @danwhy to have a call 30 minute with Fresh Egg where they share their screen in order to validate the use case for jquery specifically (as opposed to doing this with javascript)? Unless they have already been through it with you. 

@cleop Could you please add anything good further from your conversation with Elle?

**Comment by reddog** [comment]
@iteles Thanks for that.  What do you mean by

> Drops in performance

?

Do you mean page loading time?  Something else?

A simple test would be to add it and do a page load speed test.  That should give us something to go on.

**Comment by Cleop** [comment]
Thanks for updating @iteles, I forgot to record this on here following the chat with @ellemindwave yesterday.

I think the only thing I would add is that I am already aware that speed and performance is something we are trying to improve on the site (see #516 #300 for background and context) and that #516 alone is estimated to take a day's work. Given that, as @iteles mentioned, teaching the Fresh Egg team how to do what jQuery does to select DOM elements would take far less than this, it may be a more efficient use of time to simply share the knowledge with them. Perhaps less importantly but merely for consistency it may be cleaner to have the site operating with one use of js rather than two (for clarity for anyone approaching the project in the future and understanding the reasoning behind it).

**Comment by reddog** [comment]
@Cleop Thanks for that.  Maybe it would be useful to compare:

1.  time to add in jQuery and perform a page load speed test.  I can perform the page load speed test if required.
2.  time of all required participants to help Fresh Eggs learn more JavaScript?  Estimated at 30 mins for @Danwhy + Fresh Eggs staff (one or more?) = 1 hour+

Looking at the page load waterfall at https://github.com/mindwaveventures/cms/issues/516#issuecomment-335807449 it may well be that jQuery is simply loaded at the same time as some other libraries (and hence may take no extra time at all).

If there are concerns about adding the jQuery library causing confusion to others, this could be documented somewhere.

**Comment by reddog** [comment]
Had a discussion with @Cleop, @Danwhy and @katbow around two main factors:

1.  possible client-side performance hit in adding in jQuery - something else to download

2.  *cleanliness* of code stack - using jQuery for only part of the system (ie currently satisfying this requirement and https://github.com/mindwaveventures/cms/issues/692 )

Dealing with the *cleanliness* point first - there are already other technologies within the stack, eg `elm` which probably have a lower developer pool to choose from in terms of developers who may come *pre-loaded* with the tech skills required for this project.  However, developers with jQuery are fairly much in abundance and it is probably highly likely that any developer comfortable with elm would be fine with jQuery.

In terms of potential performance hit - this looks fine, see the following:

I have deployed a version of the site to the staging environment with the only change being to load in the jQuery library.

Homepage load waterfall **without** jQuery:

![image](https://user-images.githubusercontent.com/151362/31944221-3fa4274e-b8c3-11e7-8215-4f3d24e18a8c.png)


Homepage load waterfall **with** jQuery:

![image](https://user-images.githubusercontent.com/151362/31944269-5f47daf0-b8c3-11e7-9c78-eb9a46b9ea8e.png)


It looks like the jQuery library is being loaded *at the same time* as other JS and CSS files:

![image](https://user-images.githubusercontent.com/151362/31944462-18351802-b8c4-11e7-8a91-cc90da1de79b.png)

This is without considering the fact that we're loading from Google's CDN - this library will already be in many users' browser cache and hence won't be downloaded at all.  For those users who don't have a cached copy, it will be in their browser cache after the first page visited from this site.

**Comment by katbow** [comment]
@reddog can you verify what your decision is from these tests? Would you like jQuery added in based on this or not?

**Comment by reddog** [comment]
@katbow I think the load test shows there are no performance issues to be concerned with at this stage.

@Cleop's comments around describing what the tech stack is could be handled by a slight update to the repo readme, see https://github.com/mindwaveventures/cms/issues/684#issuecomment-338183429

https://github.com/mindwaveventures/cms/issues/692 might be fixable with a very short jQuery snippet, see https://github.com/mindwaveventures/cms/issues/415#issuecomment-333079027 , which would additionally benefit from continued updates from the jQuery community (in terms of newly discovered issues with future browser/device versions).

I think on that basis, it seems more of a benefit than not.

**Comment by reddog** [comment]
Not sure what there is to actually *test* here.  jQuery has been added in to the main template for the site, see https://github.com/mindwaveventures/cms/blob/942ff1e59e0277852d674a6fc443c19982a01e6a/cms/templates/base.html#L9
