### ISSUE TITLE
E24 - Icon information doesn’t collapse

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#769]
Icon information doesn’t collapse

![screen shot 2017-11-08 at 12 37 37](https://user-images.githubusercontent.com/26304634/32549492-a1ae43c4-c481-11e7-80e6-3f5053a66b60.png)

**Comment by ellemindwave** [comment]
@katbow E24 have testing this and it still doesn't work

**Comment by iteles** [comment]
@ellemindwave Do you know which browsers they tested this on so we can isolate the issue?
Thanks!

**Comment by ellemindwave** [comment]
@iteles they tested on Chrome. Thanks

**Comment by ellemindwave** [comment]
It works fine if there is just one ‘i’ icon on the page that is open. The problem arises when there is more than one ‘i’ icon, and you open one, then move to open another. After opening more than one, you cannot collapse the Information again.

**Comment by reddog** [comment]
To reproduce, go to https://www.good-thinking.uk/self-assessment and answer as follows (in order to get to a self assessment screen with multiple *i* buttons):

- myself
- female, 28
- can’t sleep due to stress (option1)
- nearly everyday
- nearly everyday
- under care of a doctor? Yes
- Yes
- Yes
- None of above
- no
- no
- no
- carer for someone else? yes
- coping with caring duties? yes

**Comment by reddog** [comment]
Current behaviour appears to be:

1.  if the currently displayed self assessment page **does not** have an *information box* showing, then clicking **any** *i* button will cause the page to re-load and display an *information box* corresponding to the button pressed.

2.  if **there is** an *information box* showing, then:
 - clicking the first *i* will cause it to be hidden.  Re-clicking the first *i* will cause the *information box* to be re-shown, whatever topic it relates to
 - clicking any other *i* will cause the self assessment page to re-load and display the *information box* for that button.

**Comment by reddog** [comment]
Seems that if we store the *a_info* value of the currently displayed information box (probably either as a hidden *input* (since there are already several of these), or an *attribute* on the *information box* HTML element, then we could check that against the *a_info* value of the *i* button being pressed and then:

1.  If an *information box* is being displayed:
 - if the *i* button being pressed has the same *a_info* value as the currently displayed *information box*, then just hide it.
 - Otherwise, perform the usual page re-load and display the newly selected *information box*.

2.  If an *information box* is not being displayed, but one has been hidden on this page then
 - if the *i* button being pressed has the same *a_info* value as the currently hidden *information box*, then just show it.
 - Otherwise, perform the usual page re-load and display the newly selected *information box*.

**Comment by reddog** [comment]
![image](https://user-images.githubusercontent.com/151362/33614991-cbd36b0c-d9d0-11e7-94b4-c749d4c590a9.png)
