### ISSUE TITLE
We are generating a lot of static files whenever we run the server

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#81]
I always have this locally after running the server:

![screen shot 2017-07-25 at 17 23 39](https://user-images.githubusercontent.com/15983736/28582639-16ab137c-715e-11e7-8679-0aed33184308.png)

Should we `gitignore` them or look to stop these being generated?

**Comment by Danwhy** [comment]
These files need to be generated, as these are the static files we use. They can be gitignored, as the live site does the same and generates them when the server starts.

But this isn't really an appropriate place for those files to go, as that directory is actually a django app. 

They're being generated in there because of [this line](https://github.com/LDMW/cms/blob/master/cms/settings/base.py#L150), but if we change that (to `staticfiles`, say), the javascript stops working. We also have to find where the path is being generated to require those files and change that, which I assume is one of the other `static` definitions in that file, I'm just not sure which one.

**Comment by samhstn** [comment]
Fixed in #97
